name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build_and_test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install GO
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
        
  generate_version:
    name: "Generate Version"
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    outputs:
      fullSemver: ${{steps.gitversion.outputs.FullSemVer}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion 
        uses: gittools/actions/gitversion/execute@v0 
        with:
          useConfigFile: true
          configFilePath: .github/version/version.yml

      - run: echo "fullSemver=${{steps.gitversion.outputs.FullSemVer}}" >> $GITHUB_OUTPUT

  git_tag_and_release:
    name: "Git Tag and Release"
    runs-on: ubuntu-latest
    needs: generate_version
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Add Git Tag"
        run: | 
            git config --global user.email "${{secrets.EMAIL}}"
            git config --global user.name "Pieeer1"
            git tag -a v${{needs.generate_version.outputs.fullSemver}} -m "Release v${{needs.generate_version.outputs.fullSemver}} "
            git push origin v${{needs.generate_version.outputs.fullSemver}} 
  
      - name: "Create Github Release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.generate_version.outputs.fullSemver}}
          release_name: Release ${{needs.generate_version.outputs.fullSemver}}
          draft: false
          prerelease: false